import type { Metadata } from "next";
import "./globals.css";
import { AvanttFont } from "@/assets/fonts";
import ThemeProvider from "@/components/ThemeProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${AvanttFont.className} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider defaultTheme="dark" attribute={"class"} enableColorScheme enableSystem>{children}</ThemeProvider>
      </body>
    </html>
  );
}
