export const BRANDS = [
  { name: "American Express", image: "/example.jpg" },
  { name: "AARP", image: "/example.jpg" },
  { name: "Porsche", image: "/example.jpg" },
  { name: "ESPN", image: "/example.jpg" },
  { name: "The Home Depot", image: "/example.jpg" },
  { name: "Moët Hennessy", image: "/example.jpg" },
  { name: "Nikon", image: "/example.jpg" },
  { name: "Kimberly-Clark", image: "/example.jpg" },
  { name: "Duracell", image: "/example.jpg" },
  { name: "Intel", image: "/example.jpg" },
  { name: "Cadillac", image: "/example.jpg" },
  { name: "Discovery", image: "/example.jpg" },
  { name: "Edward Jones", image: "/example.jpg" },
  { name: "Cotton USA", image: "/example.jpg" },
  { name: "IBM", image: "/example.jpg" },
];
export const IMAGES = [
  {
    id: 1,
    src: "/Reg No.JPG",
    speed: 0.3,
    position: "top-[5%] left-[4%] sm:top-[10%] sm:left-10",
  },
  {
    id: 2,
    src: "/Executive Lounge Chair.JPG",
    speed: 0.6,
    position: "top-[15%] right-[4%] sm:top-[20%] sm:right-10",
  },
  {
    id: 3,
    src: "/TEM09545.jpg",
    speed: 1,
    position: "top-[30%] left-[4%] sm:top-[35%] sm:left-16",
  },
  {
    id: 4,
    src: "/TEM09576.jpg",
    speed: 0.8,
    position: "top-[40%] right-[4%] sm:top-[45%] sm:right-16",
  },
  {
    id: 5,
    src: "/Middle Club Seats_Fwd Dacing.JPG",
    speed: 0.7,
    position: "top-[55%] left-[4%] sm:top-[55%] sm:left-10",
  },
  {
    id: 6,
    src: "/Middle Club Seats_Rear Facing.JPG",
    speed: 0.9,
    position: "top-[65%] right-[4%] sm:top-[65%] sm:right-10",
  },
  {
    id: 7,
    src: "/Side Pic_Left.JPG",
    speed: 0.8,
    position: "top-[75%] left-[4%] sm:top-[75%] sm:left-16",
  },
  {
    id: 8,
    src: "/Side Pic_Right.JPG",
    speed: 0.6,
    position: "top-[85%] right-[4%] sm:top-[85%] sm:right-16",
  },
  {
    id: 9,
    src: "/Side Pic_RWY.JPG",
    speed: 0.7,
    position: "top-[125%] left-[4%] sm:top-[95%] sm:left-10",
  },
  {
    id: 10,
    src: "/Side Profile.JPG",
    speed: 0.8,
    position: "bottom-[150%] right-[4%] sm:top-[105%] sm:right-10",
  },
];
